version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - dev-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=${DATABASE_HOST:-localhost}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-app}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-app}
      - DATABASE_NAME=${DATABASE_NAME:-app}
    networks:
      - dev-network
      - external-network

networks:
  dev-network:
    driver: bridge
  external-network:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_default